name: 'Build and publish to harbor'
description: 'Build and publish to IMIO container registry (harbor)'
inputs:
  HARBOR_URL:
    description: 'HARBOR_URL'
    required: true
  DELIB_HARBOR_USERNAME:
    description: 'DELIB_HARBOR_USERNAME'
    required: true
  DELIB_HARBOR_PASSWORD:
    description: 'DELIB_HARBOR_PASSWORD'
    required: true
  tags:
    description: 'Tag name'
    required: false
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
    default: Dockerfile
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.HARBOR_URL }}
        username: ${{ inputs.IMIO_HARBOR_USER }}
        password: ${{ inputs.IMIO_HARBOR_PWD }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        tags: ${{ inputs.tags }}
        platforms: linux/amd64
        pull: true
        push: true
