volumes:
  delib-postgres:
services:
  zeo:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: pm-portal-zeo
    # user: "1000:913"
    volumes:
      - ./var:/data
    command: bin/zeoserver fg
    healthcheck:
      test: [ 'CMD', 'nc', '-z', '-w5', '127.0.0.1', '8100' ]
    labels:
      - "SERVICE_NAME=website-conseil"
      - "SERVICE_TAGS=db"
      - "SERVICE_8100_CHECK_TCP=true"
      - "SERVICE_8100_CHECK_INTERVAL=300s"
      - "SERVICE_8100_CHECK_TIMEOUT=8s"
  instance:
    build:
      context: ..
      dockerfile: Dockerfile
    hostname: pm-portal-instance
    # user: "1000:913"
    volumes:
      - ./var:/data
      - ./zodbconvert.cfg:/plone/zodbconvert.cfg
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - zeo
    links:
      - zeo:db
    environment:
      - ENV=dev
      - HOSTNAME_HOST=localhost
      - ADMIN_PASSWORD=admin
      - HTTP_PORT=8081
      - ZEO_HOST=db
      - ZEO_PORT=8100
      - RELSTORAGE_DB=zope
      - RELSTORAGE_USER=zope
      - RELSTORAGE_PASSWORD=zope
      - RELSTORAGE_HOSTNAME=postgres
      - RELSTORAGE_PORT=5432
      - PLONE_EXTENSION_IDS=plone.app.caching:default,plonetheme.barceloneta:default,plonemeeting.portal.core:default
      - DEFAULT_LANGUAGE=fr
      - ACTIVE_BIGBANG=True
      - SITE_ID=conseil
      - CRON=True
  postgres:
    image: postgres:16.4
    hostname: pm-portal-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=plone
      - POSTGRES_USER=zope
      - POSTGRES_PASSWORD=zope
    volumes:
      - delib-postgres:/var/lib/postgresql/data
