name: Publish release image
on:
  workflow_dispatch:
  push:
    tags:
      - '**'

env:
  BUILD_NUMBER: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  IMAGE_NAME: delib/deliberationsbe
  IMAGE_VERSION: ${{ github.ref_name }}

jobs:
  docker:
    runs-on: gha-runners-delib-py3
    steps:
      - name: Build, push image and notify
        uses: IMIO/gha/build-push-notify@v3.9.3
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ${{ secrets.HARBOR_URL }}/${{ env.IMAGE_NAME }}:latest
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.DELIB_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DELIB_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.DELIB_MATTERMOST_WEBHOOK_URL }}
          CONTEXT: '.'
          DOCKERFILE: 'Dockerfile'
          BUILD_ARGS: 'build_number=${{ env.BUILD_NUMBER }}'