name: Publish release image
on:
  workflow_dispatch:
  create:
    tag:
env:
  IMAGE_NAME: delib/deliberationsbe
  BUILD_NUMBER: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}

jobs:
  docker:
    runs-on:
      group: self-hosted
    steps:
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.DELIB_HARBOR_USERNAME }}
          password: ${{ secrets.DELIB_HARBOR_PASSWORD }}
      - name: Build, push image and notify
        uses: IMIO/gha/build-push-notify@v3.1
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ secrets.HARBOR_URL }}/${{ env.IMAGE_NAME }}:latest
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.DELIB_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DELIB_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.DELIB_MATTERMOST_WEBHOOK_URL }}
          CONTEXT: '.'
          DOCKERFILE: 'Dockerfile'
          BUILD_ARGS: 'build_number=${{ env.BUILD_NUMBER }}'