name: Update images
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build latest
        uses: IMIO/buildout.pm.portal/actions/harbor@add-gh-actions
        with:
          HARBOR_URL: ${{ secrets.HARBOR_URL }}
          DELIB_HARBOR_USERNAME: ${{ secrets.DELIB_HARBOR_USERNAME }}
          DELIB_HARBOR_PASSWORD: ${{ secrets.DELIB_HARBOR_PASSWORD }}
          tags: "${{ secrets.HARBOR_URL }}/delib/citizenportal:latest"